"""initial schema with sweetness

Revision ID: 28d501ac74d1
Revises:
Create Date: 2026-04-29 22:03:30.047473

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "28d501ac74d1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
