"""Initial schema baseline

Revision ID: 7c95b09e85e4
Revises:
Create Date: 2026-04-29 19:15:55.415015

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c95b09e85e4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("honey_varietal", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("nutrient_protocol", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.drop_column("nutrient_protocol")
        batch_op.drop_column("honey_varietal")

    # ### end Alembic commands ###
