"""Add sweetness_target to recipes

Revision ID: bd9663dc5b3a
Revises: 28d501ac74d1
Create Date: 2026-04-29 22:06:30.225399

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bd9663dc5b3a"
down_revision: Union[str, Sequence[str], None] = "28d501ac74d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
